name: Film Tracker
description: Track my reviews against a list of films.

defaults:
  - scope:
      path: "NYT1000"
    values:
      layout: "circularstackedbarplot"
      title: "The New York Times' Essential 1,000 Films To See"
  - scope:
      path: "Oscars"
    values:
      layout: "circularstackedbarplot"
      title: "Oscar-Winning Films (in all categories)"